apiVersion: v1
kind: Namespace
metadata:
  name: kubishi-scholar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubishi-scholar
  name: kubishi-scholar-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubishi-scholar-service
      app.kubernetes.io/part-of: kubishi-scholar
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubishi-scholar-service
        app.kubernetes.io/part-of: kubishi-scholar
    spec:
      containers:
        - name: service
          image: jaredraycoleman/kubishi-research-group:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: FLASK_ENV
              value: "production"
            - name: DEPLOY_ID # for reasy re-deployment
              value: DEPLOYID-4c8aac91dba2d45a615e8264e2fd6220
            - name: SECRET_KEY # mount from secret
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
  namespace: kubishi-scholar
  name: kubishi-scholar-service
spec:
  selector:
    app.kubernetes.io/name: kubishi-scholar-service
    app.kubernetes.io/part-of: kubishi-scholar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubishi-scholar-service-ingress
  namespace: kubishi-scholar
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  rules:
    - host: research.kubishi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubishi-scholar-service
                port:
                  number: 80
  tls:
    - secretName: kubishi-scholar-service-cert
      hosts:
        - research.kubishi.com
